### ISSUE TITLE
timestep params is actually in seconds not milliseconds

### ISSUE THREAD

**Issue by Triuman** [dimforge/rapier.js#111]
In the comments and also in the documentation, it says `@param timestep - The timestep length, in milliseconds.` But it should be in seconds. It gives 0.016 as an example value for a 60 fps game. It can't be 0.016 ms. It is 0.016 second and it equals to 16 ms.

**Comment by jcyuan** [comment]
yes you are right. it's delta = 0.016 = 60fps
