### ISSUE TITLE
React physics step is twice as fast as Nodejs physics step

### ISSUE THREAD

**Issue by Triuman** [dimforge/rapier.js#112]
Package: @dimforge/rapier3d-compat
Version: v0.7.3

I have a client(React) and a server(Nodejs) which are running the same world configuration. But in the server I have to set the World.timestep double the amount I set in the client so that they have the same speed.

Does anyone know why this is happening?

**Comment by jcyuan** [comment]
what is your screen refresh Hz of your client, and server?

**Comment by jcyuan** [comment]
you can do something like this:
```
lastTime = performance.now();

step() => {
       t = lastTime - performance.now()
       console.log(t);
}
```

to check if your frame interval is the same or not, because imo if the world works then it works, unless your environment provides different calling frequent, otherise i can't imagine why...

**Comment by Triuman** [comment]
You are right! It gave me 30.5 ms even though I set the interval for 16 ms. I did this before I think with `Date.now()` and got 16ms.

I had no idea this would happen in Nodejs. Please tell me if you have any idea. But I will do a research anyways.

Thanks a lot!

**Comment by Cri5-W** [comment]
Is there a way to have a fixed time step? Like have a fixed delta time and custom loop.

**Comment by Triuman** [comment]
I will do something like that at the end but I need to figure out why my machine is running setInterval very unreliably.

**Comment by LeXXik** [comment]
@Cri5-W  
You can implement a fixed timestep as described here:
https://gafferongames.com/post/fix_your_timestep/

**Comment by jcyuan** [comment]
@Cri5-W  yes, as @LeXXik suggested, you are supposed to call your `world.step` in the callback with your fixed timestamp value set for your world.

```
......

integrate(): void {
    world.timestep = 0.016;   // this value just tells to Rapier the frame delta, it does nothing with `fixed-step-calling`, so only if your `world.step` is called in such solution it will then work.
    world.step(); 
}
```

**Comment by jcyuan** [comment]
here simply show my code as an example:

```
private stepPhysicsWorld(delta: number): void {
        const queue = this._curCase!.eventQueue;
        const hooks = this._curCase!.hooks;

        if (!this.fixedTimeStepEnabled) {
            this._world.timestep = delta;
            this._world.step(queue, hooks);
        } else {
            this._accumulator += delta;
            let substepIndex = 0;
            this._world.timestep = FixedTimeStep;

            while (substepIndex++ < this.maxSubSteps && this._accumulator > FixedTimeStep) {
                this._world.step(queue, hooks);
                this._accumulator -= FixedTimeStep;
            }
        }
    }
```
and then call this method in your game engine's update callback.

**Comment by Triuman** [comment]
Thank you both! Now, I implemented that using `setImmediate` and it works pretty well.

```
  step = () => {
    const now = performance.now();
    if(!this.lastStepTime)
      this.lastStepTime = now;
    let dt = now - this.lastStepTime;

    while(dt > this.updateInterval) {
      this.physicsWorld?.step();
      dt -= this.updateInterval;
      this.lastStepTime = now - dt;
    }

    setImmediate(this.step);
  }
```

**Comment by Cri5-W** [comment]
I don't understand. Why is there a timestep property in the world object?

The value of the timestep property by default has a value close to 1/60. Does that imply that the frequency should be 60 steps per second?

I'm just new to these physics concepts.

**Comment by jcyuan** [comment]
> 

i think you should set the `timestep` property for your world otherwise your world will alwasy use the default `timestep` to accumulate:

    this.physicsWorld?.timestep = this.updateInterval;

**Comment by jcyuan** [comment]
> I don't understand. Why is there a timestep property in the world object?
> 
> The value of the timestep property by default has a value close to 1/60. Does that imply that the frequency should be 60 steps per second?
> 
> I'm just new to these physics concepts.
> 
> Edit:
> 
> Ok, I think I just solved my problem.
> 
> I asked in the dimforge discord server and a person told me that by changing the world **timestep** property to the desired **deltaTime** then it would be pretty much it.
> 
> My problem was that it wasn't working when I did that but I realized that I assigned the timestep to **1000/30** instead of **1/30** or 30 times per second because that's how I use it to set the interval in **milliseconds** in the **setInterval** in javascript and the **timestep** property in rapier has to be in seconds.

the world will use this value you specify to accumulate the internal elapsed physics time.

**Comment by Triuman** [comment]
> > 
> 
> i think you should set the `timestep` property for your world otherwise your world will alwasy use the default `timestep` to accumulate:
> 
> ```
> this.physicsWorld?.timestep = this.updateInterval;
> ```

I set it like below since timestep is in seconds.

```
this.updateInterval = 16; //ms
this.physicsWorld.timestep = this.updateInterval / 1000; //sec
```
