### ISSUE TITLE
world.intersectionPair does not return true when colliders intersect in 0.8.0

### ISSUE THREAD

**Issue by smjnab** [dimforge/rapier.js#131]
Since 0.8.0 world.intersectionPair does not return true when the two colliders intersect. After updating to 0.8.0 from alpha release it stopped working in my current project and to verify I created a fiddle.

https://jsfiddle.net/w9yb05zp/18/

**Comment by sebcrozet** [comment]
Thank you for reporting this. It will be fixed by #132.
