### ISSUE TITLE
Rigidbody loses stability under force

### ISSUE THREAD

**Issue by LeXXik** [dimforge/rapier.js#141]
Using 0.8,1

I have a 1 kg box and I am applying a constant relatively small downward force on a fixed update:

```
body.addForce(0, -4, 0);
```

The box slowly sinks into the ground until it loses control:

https://user-images.githubusercontent.com/5677782/173255283-4cdfcdf6-01bb-4613-8ec1-a079ceb93b55.mp4

**Comment by sebcrozet** [comment]
You might want to call `resetForces` before applying the force again at next frame. Otherwise all the forces you add will add up at each frame resulting in very high total force after some time,  making the contact increasingly harder to solve.

**Comment by LeXXik** [comment]
Yes, that did it, thank you!
