### ISSUE TITLE
setGravityScale has no effect

### ISSUE THREAD

**Issue by canadaduane** [dimforge/rapier.js#181]
When calling `setGravityScale(...)` followed by `gravityScale()` on a RigidBody, the value is not stored, and the gravity does not appear to be scaled (in my case, I am trying to turn gravity off for one object, but it still has gravity):

![image](https://user-images.githubusercontent.com/129/198907540-94f6f017-9ee8-4751-afc6-df94f526f54d.png)

**Comment by sebcrozet** [comment]
I can’t seem to reproduce this issue. Which version of rapier are you using?

**Comment by canadaduane** [comment]
I apologize, it looks like I was re-creating this object every loop, so it appeared to be unaffected by setGravityScale.

**Comment by canadaduane** [comment]
I'd like to re-open this issue because I'm pretty sure I'm still seeing this problem, and wondering if anyone else can help identify a cause. I will try to write a minimum replicable. Is there a "sample harness" on a code website somewhere that I can use to try to re-create this issue in rapier.js?

**Comment by canadaduane** [comment]
Ok, I apologize once again for the noise. It's my code.
