### ISSUE TITLE
rigidBody.sleep() actually doesnt send dynamic rigidBody to sleep on first world.step() for this rigid body

### ISSUE THREAD

**Issue by AD2018** [dimforge/rapier.js#189]
Setting rigidBody to sleep with `rigidBody.sleep()` (even if i use `RigidBodyDesc.setSleeping(true)`) actually doesnt send rigid body to sleep on first `world.step()` for this rigid body. 
1) You need to create DYNAMIC rigid body with `RigidBodyDesc.setSleeping(true)` (or use `rigidBody.sleep()` after its creating, no matter what approach to use)
2) `console.log(rigidBody.isSleeping())` will return TRUE, as it is expected
3) Execute `world.step()`
4) `console.log(rigidBody.isSleeping())` will return FALSE, as it is not expected

If you make rigidBody fall asleep after that steps, it will work correctly, `console.log(rigidBody.isSleeping())` after `world.step()` will always eturn true(if there is no influence from other rigid bodies etc)

Package.json:
![image](https://user-images.githubusercontent.com/25452819/205623776-31643de7-a975-4a0a-bca4-8aeddda7a995.png)

Demonstration of issue:
1) I will skip this stage, i only will show you that rigid body actually is sleeping farther:
2)
![image](https://user-images.githubusercontent.com/25452819/204234770-537fbb6c-38ef-4a2e-9337-5b60a3bd1008.png)

2,3,4)
![image](https://user-images.githubusercontent.com/25452819/204235065-b166481c-a048-4f76-b33e-b8b59044c31a.png)

As you can see, I even used `rigidBody.sleep()` before `world.step()`, but after the first `world.step` (for this rigid body) it wake uping, no matter what did you do. Also you can see, that on the second/third/...  `world.step()` it works as it should. The problem is only with first for current rigid body `world.step()`

Also i should notice, that if I don't use `rigidBody.sleep()` before each `world.step()`, the rigid body won't sleep farther:
![image](https://user-images.githubusercontent.com/25452819/204236360-b86e7c2c-5800-4e8c-885b-39cfef48a015.png)

**Comment by AdelNorberg** [comment]
@sebcrozet Hey! 
This issue is already two months old. Is there any news about this? We can't release the game with this bug :(

**Comment by sebcrozet** [comment]
@AdelNorberg Hi! The latest version has a fix for this. Could you try it and let me know if that doesn’t work for you?

**Comment by AD2018** [comment]
@sebcrozet looks like it works, thank you
although this is no longer important since you added rigid bodies enabling and disabling(I think so, haven't tried it yet)
