### ISSUE TITLE
Kinematic controller stutters

### ISSUE THREAD

**Issue by LeXXik** [dimforge/rapier.js#191]
Moving the issue from Discord, so it can be tracked.

A kinematic character controller stutters, when sliding along the surface. Here is an X component of the input motion (left) vs the corrected motion (right):

![image](https://user-images.githubusercontent.com/5677782/207026375-0e17a5af-2636-4a52-a43d-36754f289321.png)

For some reason, controller sometimes produces a zero for a corrected motion, introducing the stutter.

A repro:
- Click Run in top left to restart, click mouse to add impulse
- Click a few times to see it stuttering

https://jsfiddle.net/LeXXik/b3m1egnd/78/

**Comment by Sceat** [comment]
Not sure if related but the kinematic controller in 3D environment is also sticky on walls and produce unpleasant effects, here is a demo I found which produce the same results I had on my own project
https://sketches.isaacmason.com/sketch/rapier/kinematic-character-controller

try to run into walls and jump on them to reproduce
