### ISSUE TITLE
Disable and enable bodies breaks behaviour 

### ISSUE THREAD

**Issue by smjnab** [dimforge/rapier.js#207]
In 0.11.1 if you disable a rigidBody and then enable it, the behaviour of the body and attached colliders will not be correct.

For example: Colliders will no longer collide properly with other colliders and the rigidBody will not be affected by gravity. Forces applied during disabled, will be applied when enabled. Possibly also bodies attached to joints experience odd behaviour if disabled/enabled.

Test sandbox: https://codesandbox.io/s/vite-rapier-pixi-ro1t44?file=/src/index.js:725-744

use testCase to test. 0 is with no disable/enable and works as intended.

**Comment by sebcrozet** [comment]
Thank you for the very detailed test case! This should be fixed by https://github.com/dimforge/rapier/pull/439

**Comment by smjnab** [comment]
Updated test sandbox to 0.17.2 and verified enable/disable working as intended.
