### ISSUE TITLE
Feature Request: Debug rendering of colliders

### ISSUE THREAD

**Issue by 8Observer8** [dimforge/rapier.js#211]
Please add debug rendering of colliders like in Box2D, Bullet Physics, Ammo.js and so on.

![182031433-cdd7145c-1957-4d53-97d4-9a0c670a2966](https://user-images.githubusercontent.com/3908473/214335149-db7de5d0-ab40-403d-9adb-2995747009e9.gif)

![212646579-77c3186d-749b-42b5-a377-8b9e46669b3d](https://user-images.githubusercontent.com/3908473/214333740-a84be23a-6aa6-4f9e-b544-20c4260bf129.gif)

![184449542-5d0a733b-2c22-4951-ae49-fae3f98c317c](https://user-images.githubusercontent.com/3908473/214333709-a61cefc4-c715-4fa7-8609-029de49103d4.gif)

**Comment by sebcrozet** [comment]
Hi! This already exists: https://github.com/dimforge/rapier.js/pull/119

**Comment by 8Observer8** [comment]
For 3D too?

**Comment by 8Observer8** [comment]
@sebcrozet could you help me here: https://stackoverflow.com/questions/75513909/drawing-colliders-with-rapier2d-compat-debugrender-returns-an-empty-array
