### ISSUE TITLE
 RuntimeError: unreachable - create Trimesh - 3D Compat - Node.js

### ISSUE THREAD

**Issue by OldManMeta** [dimforge/rapier.js#223]
Hi - I have a small method to create a rigidbody and Trimesh collider:

```
function makeTriMeshFixed(testModel: WorldSpaceGeoCollectionObject) {
            if (testModel.scenePos === undefined) return;

            try {
                let bodyDesc = new RAPIER.RigidBodyDesc(RAPIER.RigidBodyType.Fixed);
                bodyDesc.setTranslation(testModel.scenePos.x, testModel.scenePos.y, testModel.scenePos.z);

                let body = world.createRigidBody(bodyDesc);

                console.log('created body=>', body);

                world.createCollider(RAPIER.ColliderDesc.trimesh(testModel.trimeshVertices, testModel.trimeshIndicies), body);
                //body.applyImpulse({x:vx, y:vy}, true);
                return body;
            } catch (error) {
                console.log('Error in makeTriMeshFixed', error);
            }
        }

```

What you can see in the following, is that the body is created but the CreateCollider is failing:

```
Loaded Model=> test element
created body=> sA {
  rawSet: v { ptr: 1117032 },
  colliderSet: sI {
    raw: l { ptr: 1117760 },
    map: YA {
      fconv: [Float64Array],
      uconv: [Uint32Array],
      data: [],
      size: 0
    }
  },
  handle: 0,
  userData: undefined
}
Error in makeTriMeshFixed RuntimeError: unreachable
    at wasm://wasm/005602e6:wasm-function[869]:0x128477
    at wasm://wasm/005602e6:wasm-function[1363]:0x143d94
    at wasm://wasm/005602e6:wasm-function[1091]:0x1368c3
    at wasm://wasm/005602e6:wasm-function[1042]:0x13438c
    at IA.trimesh (C:\Users\mrbre\source\repos\ORCA\TESTING\FPS_Server_RAP\node_modules\@dimforge\rapier3d-compat\rapier.cjs.js:1:43113)
    at MI.intoRaw (C:\Users\mrbre\source\repos\ORCA\TESTING\FPS_Server_RAP\node_modules\@dimforge\rapier3d-compat\rapier.cjs.js:1:80163)
    at sI.createCollider (C:\Users\mrbre\source\repos\ORCA\TESTING\FPS_Server_RAP\node_modules\@dimforge\rapier3d-compat\rapier.cjs.js:1:91983)
    at eI.createCollider (C:\Users\mrbre\source\repos\ORCA\TESTING\FPS_Server_RAP\node_modules\@dimforge\rapier3d-compat\rapier.cjs.js:1:102296)
    at makeTriMeshFixed (C:\Users\mrbre\source\repos\ORCA\TESTING\FPS_Server_RAP\build\server.js:164:23)
    at Timeout.loop [as _onTimeout] (C:\Users\mrbre\source\repos\ORCA\TESTING\FPS_Server_RAP\build\server.js:131:21)
```

This is a typescript solution and I can verify that the vertices and indices collections are of both correct type and contain the correct data (taken from another rapier solution I have, where Trimesh is created correctly)

Version is:
@dimforge/rapier3d-compat": "^0.11.1"

I have no idea how to debug this further or to start to understand what the issue is.

Many thanks for any help.

**Comment by OldManMeta** [comment]
On further testing, I can see that the error looks like the create collider methods can't find the rigid bodies in the world?

After manually creating a Trimesh object and ColliderDesc object, I can confirm both of the following fail with the same error as shown above:

```
world.createCollider(tempColliderDesc, body);
world.colliders.createCollider(world.bodies, tempColliderDesc, body.handle);

```

**Comment by LeXXik** [comment]
Make sure `testModel.trimeshVertices` and `testModel.trimeshIndicies` have correct data and of the right types - Float32 and Uint32. Refer to API:
https://rapier.rs/javascript3d/classes/ColliderDesc.html#trimesh

**Comment by OldManMeta** [comment]
@LeXXik Thanks for your response - 

I've validated my data types, in fact the same arrays are used to build a trimesh successfully using another client app implementing rapier, so I know for sure that the rapier js compat library works, because react-three-fiber uses it to provide their rapier implementation.

I'm really sure it is something stupid I am doing, but those WASM error messages are total jank and I'm unable to follow the source code enough to perhaps discover my issue(s) or create a PR to help out.

I'll post any success back here for other, unless someone is able to post a pointer for me before hand.

Cheers

**Comment by LeXXik** [comment]
Well, I just noticed your code here is using Float64Array, when it should be 32. I don't know what that code does though, so just wanted to point that the types are important.

![image](https://user-images.githubusercontent.com/5677782/223138619-5ff9548e-dc45-4699-8ddf-bbde5a7a7a4b.png)

**Comment by OldManMeta** [comment]
Thanks so much @LeXXik 

I've just forked a codesandbox that is related to this as well - in that, I've explicitly created the verts and indicies from arrays, and I noticed that it is still Float64Array as well. Which is pretty strange.

https://codesandbox.io/p/sandbox/rapier3d-compat-mininmal-node-example-forked-4i76gr?file=%2Findex.js&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A95%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A95%7D%5D

**Comment by OldManMeta** [comment]
I'm going to close this out, as it's related into the same issue #224
