### ISSUE TITLE
WASM - Not sure this even working

### ISSUE THREAD

**Issue by OldManMeta** [dimforge/rapier.js#224]
Hi - I've been adding a few issues here and generally trying to get some answers on things - I really appreciate the effort that's gone into the project thus far.

I need to get this running on a node.js server.

I've tried so many different ways, that I am not sure what is working and what isn't.

A previous issue I posted appeared to load the compat 3D libraries correctly, but regardless of how I approached it, I could not create Trimesh or complex mesh colliders without hitting a WASM error.

I then tried to create a new node solution with webpack, hoping I could bundle the non-compat version of the library into it and get around the trimesh issues - but that also appears to have issues around WASM not being correctly added to the project, even though the solution builds correctly with webpack. At runtime, it simply kills the app with a "Can't find the module @dimforge/rapier3d" error.

It would be super cool to get this working - but I am now just unsure if it is even possible with Rapier, JS and Node.

My question is for anyone out there, has anyone actually got this to work in Node?

Many thanks for any help and pointers.

**Comment by isaac-mason** [comment]
I've previously used `@dimforge/rapier3d-compat` with node without issues, but that was a few versions ago.

If you can share a minimal reproduction of the issue that would be helpful.

**Comment by isaac-mason** [comment]
Here's a minimal example demonstrating using `@dimforge/rapier3d-compat` with node: https://codesandbox.io/p/sandbox/rapier3d-compat-mininmal-node-example-rim59y

**Comment by OldManMeta** [comment]
@isaac-mason - thanks for providing your demo. I'll throw it into my code, and if the cuboid creates, then it's something to do with the Trimesh in the lib. If not, then it's definitely me. I'm trying to clean up a file to share as well. BRB. Cheers

**Comment by isaac-mason** [comment]
Ok cool! If you can reproduce a trimesh creation issue in a fork of that codesandbox / some other means that would be super helpful.

**Comment by OldManMeta** [comment]
@isaac-mason - the cuboid works, so that narrows it down. My creation of RAPIER is working if nothing else.

I've just got to grab some simple values for a Trimesh and I'll fork it. Thanks so much for this help.

**Comment by OldManMeta** [comment]
@isaac-mason Here is the fork - shows the same error:

https://codesandbox.io/p/sandbox/rapier3d-compat-mininmal-node-example-forked-4i76gr?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A17%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A17%7D%5D

Cheers

**Comment by isaac-mason** [comment]
Cheers for the repro! That will help get to the bottom of this for sure.

I used the same code in the testbed3d trimesh demo to create a dynamic trimesh, and that appears to be working: https://codesandbox.io/p/sandbox/rapier3d-compat-mininmal-node-example-forked-cdud5h

So the issue doesn't occur when creating *any* trimesh.

**Comment by OldManMeta** [comment]
@isaac-mason That's super helpful. I'm narrowing this down - I am really sure that the way I am creating the arrays is incorrect, though I do not see the problem immediately.

This is the process:

1. create a new empty project in Blender with a cube in the center. Export that as glb
2. Import that into a react application with r3f
3. Get the verts and indi collections from that model

I use this code to extrac (where rootObject is the scene imported by the gltf loader)t:

```
var childGeo = (rootObject.children[0] as Mesh).geometry;
const tmVerts = childGeo.attributes.position.array;
const indices:ArrayLike<number> =  Object.keys(tmVerts).map(Number);

var vertsFinalArray = new Float32Array(tmVerts);
var indiFinalArray = new Uint32Array(indices);

```

That returns me two arrays of 71 items each.

71 - That makes no sense to me, since this is a cube model we are talking about.

Shouldn't I just have 8 verticies and 20 indicies?

**Comment by OldManMeta** [comment]
@isaac-mason - THANK YOU GOOD SIR!

OK - for the benefit of anyone else hitting similar issues:

Firstly, better error messaging from the package would be super helpful. This really is a fight in the dark.

What caused my problem is a combination of issues - but it comes back to the format of the array collections being parsed.

Firstly, generating the Float32Array. The following line of code, actually generates an "Indexed" array, which is not what we are after:

`const tmVerts = childGeo.attributes.position.array;`

When sending that over a wire, with compression and conversions, trying to hydrate the values on the other side (in this case a Node server), we get a malformed array, that is not a Float32Array

It results in an array looking something like: array{ "0":1, "1":-1 .....}

I am not sure why this happens when the tmVerts type is shown as an ArrayLike<Number> in Typescript.

We need to further extract the vert information from the returned array to get a clean and pure number based array:

```
        var cleanVertsArray:number[]=[];
        
        for (let index = 0; index < tmVerts.length; index++) {
            const element = tmVerts[index];
            cleanVertsArray.push(element);
        }

```
Now we have a number array - e,g, array[1,-1,0 ....]

We have similar problems with the Indicies.

This line of code does not actually get the Indicies, it simply gets the Index's of the verticies:

`const indices:ArrayLike<number> =  Object.keys(tmVerts).map(Number);
`
We need to rip the correct Indicies from the geometry itself:

```
       const index = childGeo.getIndex();
        var cleanIndiArray:number[]=[];

        for ( let i = 0; i < index.count; i += 3 ) {

            const a = index.getX( i );
            const b = index.getX( i + 1 );
            const c = index.getX( i + 2 );

            cleanIndiArray.push(a,b,c);
        }

```

Again, now this results in a proper formatted number based array.

On the Server side, before constructing the Trimesh, we can convert the two number arrays correctly using:
```

  var verticiesArray: Float32Array = new Float32Array(cleanVertsArray);
  var indiciesArray: Uint32Array = new Uint32Array(cleanIndiArray);


```

We are now able to test the Collider has been created and added.

**Comment by isaac-mason** [comment]
Glad you were able to get to the bottom of your issue! 🙂
