### ISSUE TITLE
ReferenceError: Buffer is not defined in init.ts

### ISSUE THREAD

**Issue by wwwtyro** [dimforge/rapier.js#40]
In 0.7.1 (3d-compat), I'm seeing this error:

```Uncaught (in promise) ReferenceError: Buffer is not defined```

While awaiting `Rapier.init()`.

`Buffer` seems undefined in this commit, but not sure if there's some global definition somewhere: https://github.com/viridia/rapier.js/blob/40ef3dc75208f1936ac3b41520e99d8dec20d805/rapier-compat/src3d/init.ts#L10

Seems like it's gone in `master`: https://github.com/viridia/rapier.js/blob/master/rapier-compat/src3d/init.ts

So maybe it just needs a new version pushed? Or maybe I'm importing incorrectly - neither of the following work for me:

```ts
import * as Rapier from "@dimforge/rapier3d-compat";

async function main() {
    await Rapier.init();
}
```

```ts
import Rapier from "@dimforge/rapier3d-compat";

async function main() {
    await Rapier.init();
}
```

The first one worked in 0.7.0. Thanks for any help!

**Comment by sebcrozet** [comment]
> So maybe it just needs a new version pushed?

You are right, we need to make a new release for `rapier-compat`. I’ll do that in a minute.

**Comment by sebcrozet** [comment]
The 0.7.2 release of `rapier-compat` is done. Does it solve your issue @wwwtyro?

**Comment by wwwtyro** [comment]
Works like a charm now, thanks for that!
