### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by jcyuan** [dimforge/rapier.js#56]
Env: Win10 PC

execute `cargo build --release` in folder `rapier.js\rapier2d` gives this:

![image](https://user-images.githubusercontent.com/850854/148509634-ad5b10aa-20d4-401b-899f-25d4774382cd.png)

same error for both 2d & 3d.

am i doing something wrong?

**Comment by sebcrozet** [comment]
Hi! You need to use `wasm-pack build` instead of `cargo` (see the `rapier2d/build_rust.sh` file.
In order to install `wasm-pack`, you can run `cargo install wasm-pack`.

**Comment by jcyuan** [comment]
got it, thanks so much!
