### ISSUE TITLE
[bug] Segment does not return start / end point

### ISSUE THREAD

**Issue by jcyuan** [dimforge/rapier.js#60]
![image](https://user-images.githubusercontent.com/850854/148658087-5ada6240-953b-48a4-b11d-697fb84fffda.png)

1, here if i want to retrieve the start point / end point of a segment (the `c`)
it returns undefined.

`c.a`, `c.b`, `c.vertices()` all returns undefined

2, triangle shape does not return `a,b,c` too
`c.a, c.b, c.c`, `c.vertices()`, all returns undefined

3, all rounded shape, if you want to retrieve its round radius, all undefined
for example `roundCuboid.roundRadius()` will return undefined

**Comment by jcyuan** [comment]
createSegment(v0: Vector, v1: Vector, x?: number, y?: number, type?: RigidBodyType | RigidBody): RigidBody | Collider {
        let body: RigidBody | undefined = undefined;

        if (type !== undefined) {
            if (type instanceof RigidBody)
                body = type;
            else
                body = this.createBody(type, x, y);
        }
        
        const desc = ColliderDesc.segment(v0, v1);
        const collider = this._world.createCollider(desc, body ? body.handle : undefined);

        return body || collider;
    }

    this.createSegment(VectorOps.new(0, 0), VectorOps.new(1, 0), RigidBodyType.Dynamic);

this is the code to create it.

**Comment by sebcrozet** [comment]
Fixed by #88.
