### ISSUE TITLE
[bug] 0.8.0-alpha, failed to create a impulse joint.

### ISSUE THREAD

**Issue by jcyuan** [dimforge/rapier.js#68]
const staticCenterBody = context.createBody(RigidBodyType.Static);

        const tumblerBox = context.createBody(RigidBodyType.Dynamic);

        const ballJointParam = JointData.revolute(VectorOps.new(cx, cy), VectorOps.new(cx, cy));
        const ballJoint = context.world.createImpulseJoint(ballJointParam, staticCenterBody, tumblerBox) as RevoluteImpulseJoint;
        ballJoint.configureMotorVelocity(cfg.angularVelocity, cfg.angularVelocity);
        
![image](https://user-images.githubusercontent.com/850854/150928335-cd4f7410-0e15-4614-85c2-60c51fbdce04.png)

**Comment by sebcrozet** [comment]
Hi! This looks like a bug. Joints are in a slightly unstable place with this alpha release.

**Comment by jcyuan** [comment]
fixed by #77
