### ISSUE TITLE
[bug] 0.8.0-alpha the returned `witness1` from shape casting is not normalized.

### ISSUE THREAD

**Issue by jcyuan** [dimforge/rapier.js#69]
the `witness1` of `ShapeColliderTOI` is not normalized.

![image](https://user-images.githubusercontent.com/850854/150929028-ba2a96a7-c602-4a22-b616-87d8456ee7fb.png)

the blue arrow is `witness1`.

**Comment by sebcrozet** [comment]
Hi! The `witness1` is a point:
![image](https://user-images.githubusercontent.com/1734958/150940733-a909e467-0ab2-4b94-bf8e-bd8e10f18dfd.png)
So it is not supposed to be normalized.
Did you mean to use `normal1`?

**Comment by jcyuan** [comment]
> Hi! The `witness1` is a point: ![image](https://user-images.githubusercontent.com/1734958/150940733-a909e467-0ab2-4b94-bf8e-bd8e10f18dfd.png) So it is not supposed to be normalized. Did you mean to use `normal1`?

i got it, thanks a lot, actually i don't understand what is a `witness` 🤦‍♂️
could you help to elaborate a little more about it please? thanks so much.
