### ISSUE TITLE
Invalid Collider.activeHooks return type

### ISSUE THREAD

**Issue by cryo2010** [dimforge/rapier.js#70]
I noticed when using `@dimforge/rapier2d` that the `Collider.activeHooks()` return type was `void` when it should be `ActiveHooks`. I'm not familiar with the Rapier build process, so I hope this is the correct repo to propose a fix.

**@dimforge/rapier2d/geometry/collider.d.ts:**
```javascript
107     /**
108      * Get the physics hooks active for this collider.
109      */
110     activeHooks(): void;
```

**Patch:**
```
diff --git a/src.ts/geometry/collider.ts b/src.ts/geometry/collider.ts
index 5f0220e..b2e1642 100644
--- a/src.ts/geometry/collider.ts
+++ b/src.ts/geometry/collider.ts
@@ -192,7 +192,7 @@ export class Collider {
     /**
      * Get the physics hooks active for this collider.
      */
-    public activeHooks() {
+    public activeHooks(): ActiveHooks {
         return this.rawSet.coActiveHooks(this.handle);
     }
```

**Comment by jcyuan** [comment]
![image](https://user-images.githubusercontent.com/850854/154183870-c39d1af7-a516-495c-8a67-78351180e6c6.png)

what version you are using?

from 0.8-alpha there is no such issue.

**Comment by cryo2010** [comment]
Hi @jcyuan . This issue exists in the current NPM `@dimforge/rapier2d` package version `0.8.0-alpha.1`. 

Steps to Reproduce:
```
# Install Rapier2D
cryo@pc rapier_test % npm install --save @dimforge/rapier2d

# Search for "activeHooks" function signature
cryo@pc rapier_test  % ag "public activeHooks" node_modules/@dimforge/rapier2d
node_modules/@dimforge/rapier2d/src/geometry/collider.ts
191:    public activeHooks() {

# Get package version
cryo@pc rapier_test  % ag version node_modules/@dimforge/rapier2d/package.json
7:  "version": "0.8.0-alpha.1",
```

**Comment by jcyuan** [comment]
[rapier2d-compat.zip](https://github.com/dimforge/rapier.js/files/8204934/rapier2d-compat.zip)

this is the newest version from master branch build myself, you may try it.

i don't see this error

**Comment by cryo2010** [comment]
Thanks for looking into this. It seems the issue was fixed without using an explicit return type on the activeHooks function.
