### ISSUE TITLE
Use joint motors without TypeScript

### ISSUE THREAD

**Issue by yepw** [dimforge/rapier.js#74]
Hi, I have been trying to build a robot simulator with Rapier.js. Thanks for the great tool.

I was trying to use joint motors. Here is how to use them in the [documentation](https://rapier.rs/docs/user_guides/javascript/joints#joint-motors): 
```
let joint = world.createImpulseJoint(params, body1, body2);
(joint as RAPIER.PrismaticImpulseJoint).configureMotorVelocity(1.0, 0.5);
```
`(joint as RAPIER.PrismaticImpulseJoint)` seems like a TypeScript grammar, but my project is in vanilla JavaScript, so the webpack complains about the grammar. 

I wonder whether there is way to use joint motors without TypeScript?

I tried to use `joint.rawSet.jointConfigureMotorPosition`, but I couldn't find `RawJointAxis`, which is the second parameter of that function.

**Comment by jcyuan** [comment]
this is something related to dev problem, you can just remove all the TS definition it will work.
for example

    let joint = world.createImpulseJoint(params, body1, body2);
    joint.configureMotorVelocity(1.0, 0.5);

**Comment by yepw** [comment]
Thanks, @jcyuan. It's still not working because of #68. I tried to follow #73 to fix it, but `joint.configureMotorVelocity` is still `undefined`. Hope the bug can be fixed soon.

**Comment by jcyuan** [comment]
#77  fixed
