### ISSUE TITLE
world.createImpuselJoint() returns undefined if the joint is revolute.

### ISSUE THREAD

**Issue by smjnab** [dimforge/rapier.js#83]
This is when using 0.8.0-alpha.1 @dimforge/rapier2d
Previously it has worked as intended and returned the created joint.

If taking the example from the docs:

```
let params = RAPIER.JointData.revolute({ x: 0.0, y: 1.0 }, { x: 0.0, y: -3.0 });
let joint = world.createImpulseJoint(params, body1, body2);
```

joint would be undefined if trying to create a revolute joint. It works fine when using fixed or prismatic. The joint is created and can be found in the world using world.impulseJoints.forEachJointHandle or world.impulseJoints.forEachJoint, but world.impulseJoints.get() will return undefined.

**Comment by jcyuan** [comment]
this is already fixed but not released yet, you can manually build from master branch and have a try, it's not yet published onto NPM.

**Comment by smjnab** [comment]
Thank you for quick reply. I checked the issues, but forgot to check the solved issues!
