### ISSUE TITLE
RAPIER.JointType.Revolute enmu is 0 but should be 3

### ISSUE THREAD

**Issue by smjnab** [dimforge/rapier.js#84]
@dimforge/rapier2d 0.8.0-alpha.1

The enum for RAPIER.JointType.Revolute has a value of 0, but the .type() method on a revolute joint returns 3.

**Comment by jcyuan** [comment]
it was fixed. #77

**Comment by smjnab** [comment]
Thank you for quick reply. I checked the issues, but forgot to check the solved issues!
