### ISSUE TITLE
Undefined methods for limits

### ISSUE THREAD

**Issue by smjnab** [dimforge/rapier.js#85]
@dimforge/rapier2d 0.8.0-alpha.1

I was having problems getting limits to work properly with a prismatic joint, while trying to figure it out it seems that the following methods: limitsEnabled, limitesMax and LimitsMin are undefined.

According to the typescript these should be there. The same is true for the Revolute joint, typescript says they should be there, but they appear to be undefined.

**Comment by jcyuan** [comment]
https://github.com/dimforge/rapier.js/blob/87b85175fba9cb8c2a3295e0d40da3f5cf59f550/src/dynamics/impulse_joint.rs#L50-L64

it's just there.

can you share your error info? 
maybe you have undefined returned by `create` method?

**Comment by smjnab** [comment]
Ah, OK issue is using world.forEachJoint(). That method always gives you an impulseJoint regardless of what the joints actually are. This was what I was using.

If you create a prismatic joint with world.CreateImpulseJoint() the returned joint will properly be a PrismaticImpulseJoint and the limit methods are there. Same is true if you use world.getImpulseJoint(handle), world.impulseJoints.get(handle) to retrieve the joint.

**Comment by jcyuan** [comment]
> world.forEachJoint().

hi, could you please share your code here, because it seems there is no `world.forEachJoint()` API.

**Comment by jcyuan** [comment]
just had a quick review in the source code, but found nothing wrong...
better share a simple demo please.

**Comment by smjnab** [comment]
Demo: https://jsfiddle.net/1rtLmnd9/

Code from demo:
```
import RAPIER from "https://cdn.skypack.dev/@dimforge/rapier2d-compat";

RAPIER.init().then(() => {
    // World
    let gravity = { x: 0.0, y: -9.81 };
    let world = new RAPIER.World(gravity);

    // Rigibodies
    let rigidBodyDesc1 = RAPIER.RigidBodyDesc.newDynamic().setTranslation(0.0, 1.0);
    let rigidBodyDesc2 = RAPIER.RigidBodyDesc.newDynamic().setTranslation(0.0, 2.0);
    let rigidBody1 = world.createRigidBody(rigidBodyDesc1);
    let rigidBody2 = world.createRigidBody(rigidBodyDesc2);

    // Joint
    let jointData = RAPIER.JointData.prismatic({ x: 0, y: 0 }, { x: 0, y: 0 }, { x: 0, y: 1 });
    jointData.limitsEnabled = true;
    jointData.limits = [-2.0, 5.0];

    let joint = world.createImpulseJoint(jointData, rigidBody1, rigidBody2);

    // Debug
    console.log("direct: " + joint.limitsEnabled); // Prints function
    console.log("get: " + world.impulseJoints.get(0).limitsEnabled); // Prints function
    world.impulseJoints.forEachJoint(joint => console.log("forEachObjectVerification: " + joint)); // Verify object is retrieved
    world.impulseJoints.forEachJoint(joint => console.log("forEach: " + joint.limitsEnabled)); // Prints undefined
});
```

I don't use rapier2d-compat in my own project, so it is not an issue specific to it.

**Comment by smjnab** [comment]
> > world.forEachJoint().
> 
> hi, could you please share your code here, because it seems there is no `world.forEachJoint()` API. did you mean `world.impulseJoints.forEachJoint`?
Yes that is what I meant. Sorry for being sloppy.

**Comment by jcyuan** [comment]
hi ,fixed
